export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_JZ = 'INIT_JZ'
export const CHANGE_ICON = 'CHANGE_ICON'
export const GET_CURRENCY_LIST_FETCH_JZ = 'GET_CURRENCY_LIST_FETCH_JZ'
export const CHANGE_EXCHANNGE_JZ = 'CHANGE_EXCHANNGE_JZ'
export const CLOSE_OR_OPEN_PERIED_FETCH = 'CLOSE_OR_OPEN_PERIED_FETCH'
export const CALCULATE_FROM_SEARCH_JUMP_TO_EDIT = 'CALCULATE_FROM_SEARCH_JUMP_TO_EDIT'
export const CALCULATE_FROM_SEARCH_JUMP_TO_JZCB = 'CALCULATE_FROM_SEARCH_JUMP_TO_JZCB'

export const GET_PERIOD_FETCH = 'GET_PERIOD_FETCH'
