export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_YLLS = 'INIT_YLLS'
export const GET_YLLS_BUSINESS_DATA = 'GET_YLLS_BUSINESS_DATA'
export const CANCEL_YLLS_VISIBLE = 'CANCEL_YLLS_VISIBLE'
