export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_FCMXB = 'INIT_FCMXB'
export const AFTER_GET_FC_MXB_NO_ACLIST = 'AFTER_GET_FC_MXB_NO_ACLIST'
export const GET_FC_MXB_ACLIST = 'GET_FC_MXB_ACLIST'
export const GET_FC_DETAIL_FETCH = 'GET_FC_DETAIL_FETCH'
export const CHANGE_TREE_SELECTED_KEYS_FC = 'CHANGE_TREE_SELECTED_KEYS_FC'
export const CHANGE_FC_MXB_CHOOSR_MORE_PERIODS = 'CHANGE_FC_MXB_CHOOSR_MORE_PERIODS'
