export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ASS_KMYEB = 'INIT_ASS_KMYEB'
export const SHOW_ASS_KMYEB_CHILD_ITIEM = 'SHOW_ASS_KMYEB_CHILD_ITIEM'
export const CHANGE_ASS_KMYE_CHOOSE_MORE_PERIODS = 'CHANGE_ASS_KMYE_CHOOSE_MORE_PERIODS'
export const GET_ASS_TREE = 'GET_ASS_TREE'
export const GET_ASS_KMYEB_LIST_FETCH = 'GET_ASS_KMYEB_LIST_FETCH'
export const ASS_YEB_SHOW_ALL = 'ASS_YEB_SHOW_ALL'
export const CHECK_HAVE_DOUBLE_ASS = 'CHECK_HAVE_DOUBLE_ASS'
