export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_DETAIL_LIST = 'GET_DETAIL_LIST'
export const INIT_DETAIL_ACCOUNT_LIST = 'INIT_DETAIL_ACCOUNT_LIST'
export const GET_RUNNING_CATEGORY_DETAIL = 'GET_RUNNING_CATEGORY_DETAIL'
export const CHANGE_DETAIL_ACCOUNT_COMMON_STRING = 'CHANGE_DETAIL_ACCOUNT_COMMON_STRING'
export const CHANGE_LSMX_MORE_PERIODS = 'CHANGE_LSMX_MORE_PERIODS'
export const INIT_LSMXB = 'INIT_LSMXB'
