export const INIT_ACCOUNT_MXB = 'INIT_ACCOUNT_MXB'

export const GET_ACCOUNT_DETAIL_CATEGORY_DETAIL = 'GET_ACCOUNT_DETAIL_CATEGORY_DETAIL'
export const GET_ACCOUNT_DETAIL_LIST = 'GET_ACCOUNT_DETAIL_LIST'
export const CHANGE_ACCOUNT_DETAIL_COMMON_STRING = 'CHANGE_ACCOUNT_DETAIL_COMMON_STRING'
export const CHANGE_ACCOUNT_MXB_CHOOSE_VALUE = 'CHANGE_ACCOUNT_MXB_CHOOSE_VALUE'
export const CHANGE_ACCOUNT_MXB_ACCOUNT_TYPE = 'CHANGE_ACCOUNT_MXB_ACCOUNT_TYPE'
