export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_ZH_BALANCE_LIST = 'GET_ZH_BALANCE_LIST'
export const ACCOUNTCONF_XM_BALANCE_TRIANGLE_SWITCH = 'ACCOUNTCONF_XM_BALANCE_TRIANGLE_SWITCH'
export const CHANGE_ZHYE_MORE_PERIODS = 'CHANGE_ZHYE_MORE_PERIODS'
export const INIT_XMYEB = 'INIT_XMYEB'
export const GET_XM_BALANCE_LIST = 'GET_XM_BALANCE_LIST'
export const CHANGE_XMYE_COMMON_STRING = 'CHANGE_XMYE_COMMON_STRING'
export const XMYE_MENU_DATA = 'XMYE_MENU_DATA'
