export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_BALANCE_LIST = 'GET_BALANCE_LIST'
export const ACCOUNTCONF_BALANCE_TRIANGLE_SWITCH = 'ACCOUNTCONF_BALANCE_TRIANGLE_SWITCH'
export const CHANGE_LSYE_MORE_PERIODS = 'CHANGE_LSYE_MORE_PERIODS'
export const INIT_LSYEB = 'INIT_LSYEB'
