export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_SECURITY = 'INIT_SECURITY'
export const GET_SECURITY_PERMISSION_LIST = 'GET_SECURITY_PERMISSION_LIST'
export const DELETE_SECURITY_PERMISSION_EMPL = 'DELETE_SECURITY_PERMISSION_EMPL'
export const CHANGE_SECURITY_PERMISSION_LIST = 'CHANGE_SECURITY_PERMISSION_LIST'
export const AFTER_CHANGE_LOCK_SECRET = 'AFTER_CHANGE_LOCK_SECRET'
