export const taxRateList = [
    {key: '2%', value: 2},
    {key: '3%', value: 3},
    {key: '4%', value: 4},
    {key: '5%', value: 5},
    {key: '6%', value: 6},
    {key: '9%', value: 9},
    {key: '10%', value: 10},
    {key: '11%', value: 11},
    {key: '12%', value: 12},
    {key: '13%', value: 13},
    {key: '16%', value: 16},
    {key: '17%', value: 17}
]
export const smallTaxRateList = [
    {key: '2%', value: 2},
    {key: '3%', value: 3},
    {key: '5%', value: 5},
]
// export const manageType = {
//     "内部转账": 'LB_ZZ',
//     "收付管理": 'LB_SFGL',
//     "货物成本结转": 'LB_JZCB',
//     "发票认证": 'LB_FPRZ',
//     "开具发票": 'LB_KJFP',
//     "转出未交增值税": 'LB_ZCWJZZS',
//     "项目公共费用分摊": 'LB_GGFYFT',
//     "长期资产结转损益": 'LB_JZSY',
//     "长期资产折旧摊销": 'LB_ZJTX'
// }
export const runningType = {
    "LX_SR":'收入',
    "LX_ZC":'支出',
    "LX_JZCB":'结转成本',
    "LX_CBTH":'成本退回',
    "LX_ZZS_YKP":'已开发票',
    "LX_ZZS_WKP":'未开发票',
    "LX_ZZS_YRZ":'已认证发票',
    "LX_ZZS_WRZ":'未认证发票',
    "LX_TSSF_YKP":'已开发票',
    "LX_TSSF_WKP":'未开发票',
    "LX_TGSF_YRZ":'已认证发票',
    "LX_TGSF_WRZ":'未认证发票',
    "LX_YYSR":'营业收入',
    "LX_PP":'预收款',
    "LX_ZZS":'增值税',
    "LX_YYTS":'退售',
    "LX_TSSF":'退售税费',
    "LX_ARHX":'应收核销',
    "LX_PPHX":'预收核销',
    "LX_TSHX":'退售核销',
    "LX_YYZC":'营业支出',
    "LX_AP":'预付款',
    "LX_ADV":'应付款',
    "LX_YYTG":'退购',
    "LX_TGSF":'退购税费',
    "LX_APHX":'应付核销',
    "LX_ADVHX":'预付核销',
    "LX_TGHX":'退购核销',
    "LX_FYZC":'费用支出',
    "LX_JTGZXJ":'计提工资',
    "LX_GZXJZC":'工资支出',
    "LX_DKGJJ":'代扣公积金',
    "LX_DKSHBX":'代扣社保',
    "LX_DKSDS":'代扣所得税',
    "LX_JTSB":'计提社保',
    "LX_SBZC":'社保支出',
    "LX_DJSB":'代缴社保',
    "LX_JTGJJ":'计提公积金',
    "LX_GJJZC":'公积金支出',
    "LX_DJGJJ":'代缴公积金',
    "LX_FLFZC":'福利费支出',
    "LX_JTQTXC":'计提其他薪酬',
    "LX_QTXC":'其他薪酬支出',
    "LX_YJSF":'预交税费',
    "LX_ZZSZC":'增值税支出',
    "LX_YJDK":'预交抵扣',
    "LX_ZCSDS":'转出所得税',
    "LX_SDSZC":'所得税支出',
    "LX_JTSF":'计提税费',
    "LX_QTSFZC":'其他税费支出',
    "LX_YYWSR":'营业外收入',
    "LX_YYWZC":'营业外支出',
    "LX_ZSKX":'暂收款项',
    "LX_ZSHX":'暂收核销',
    "LX_ZFKX":'暂付款项',
    "LX_ZFHX":'暂付核销',
    "LX_ZCGJ":'资产购进',
    "LX_ZCCZ":'资产处置',
    "LX_JZSY":'处置损益',
    "LX_QDJK":'取得借款',
    "LX_CHLX":'偿还利息',
    "LX_CHBJ":'偿还本金',
    "LX_DWTZ":'对外投资',
    "LX_QDSY":'取得收益',
    "LX_SHTZ":'收回投资',
    "LX_ZZ":'增资',
    "LX_LRFP":'利润分配',
    "LX_JZ":'减资',
    "LX_JZSY_SY":"结转收益",
    "LX_JZSY_SS":"结转损失",
    "LX_JZSY_ZCYZ":"资产原值",
    "LX_JZSY_ZJTX":"累计折旧摊销",
    "LX_JZSY_SJGZ":"升级改造",
    "LX_JZSY_QLSR":"清理收入",
    'LX_FPRZ_CG': '采购发票认证',
    'LX_FPRZ_TG': '退购发票认证',
    'LX_KJFP_XS': '销售开票',
    'LX_KJFP_TS': '退售开票',
    'LX_ZCWJZZS': '转出未交税费',
    'LX_ZFLR': '支付利润',
    'LX_TZ_JTGL': '计提股利',
    'LX_TZ_SRGL': '收入股利',
    'LX_TZ_JTLX': '计提利息',
    'LX_TZ_SRLX': '收入利息',
    'LX_JK_JTLX': '计提利息',
    'LX_JK_ZFLX': '支付利息',
    'LX_NBZZ': '内部转账',
    'LX_NBZR': '内部转账-转入',
    'LX_NBZC': '内部转账-转出',
    'LX_GRSFZC': '个人税费支出',
    'LX_XMGGFYFT': '费用分摊',
    'LX_ZJTX': '折旧摊销'
}
