export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_YLLS = 'INIT_YLLS'
export const GET_PREVIEW_RUNNING_BUSINESS_FETCH = 'GET_PREVIEW_RUNNING_BUSINESS_FETCH'
export const GET_PREVIEW_NEXT_RUNNING_BUSINESS_FETCH = 'GET_PREVIEW_NEXT_RUNNING_BUSINESS_FETCH'
export const GET_PREVIEW_RELATED_RUNNING_BUSINESS_FETCH = 'GET_PREVIEW_RELATED_RUNNING_BUSINESS_FETCH'
export const CANCEL_YLLS_VISIBLE = 'CANCEL_YLLS_VISIBLE'
