export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_AMMXB = 'INIT_AMMXB'
export const AFTER_GET_SUBSIDIARY_LEDGER_AM_FETCH = 'AFTER_GET_SUBSIDIARY_LEDGER_AM_FETCH'
export const AFTER_GET_SUBSIDIARY_LEDGER_FETCH_NOAC_AM = 'AFTER_GET_SUBSIDIARY_LEDGER_FETCH_NOAC_AM'
export const GET_AMMXB_ACLIST = 'GET_AMMXB_ACLIST'
export const GET_AMMXB_ASSLIST = 'GET_AMMXB_ASSLIST'
export const CHANGE_AMXB_CHOOSE_MORE_PERIODS = 'CHANGE_AMXB_CHOOSE_MORE_PERIODS'
