export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_EIDT_CALCULATE = 'INIT_EIDT_CALCULATE'
export const CHANGE_EIDT_CALCULATE_COMMON_STATE = 'CHANGE_EIDT_CALCULATE_COMMON_STATE'
export const SELECT_EDIT_CALCULATE_ITEM = 'SELECT_EDIT_CALCULATE_ITEM'
export const SELECT_EDIT_CALCULATE_ITEM_ALL = 'SELECT_EDIT_CALCULATE_ITEM_ALL'
export const AFTER_GET_EDIT_CALCULATE_COMMON_LIST = 'AFTER_GET_EDIT_CALCULATE_COMMON_LIST'
export const GET_EDIT_CALCULATE_TRANSFER_OUT_LIST = 'GET_EDIT_CALCULATE_TRANSFER_OUT_LIST'
// export const AFTER_SUCCESS_INSERT_CALCULATE_CARRYOVER_ITEM = 'AFTER_SUCCESS_INSERT_CALCULATE_CARRYOVER_ITEM'
// export const AFTER_SUCCESS_INSERT_CALCULATE_INVOICEAUTH_ITEM = 'AFTER_SUCCESS_INSERT_CALCULATE_INVOICEAUTH_ITEM'
export const CHANGE_EDIT_ACCOUNT_ACCOUNT_NAME = 'CHANGE_EDIT_ACCOUNT_ACCOUNT_NAME'
export const INIT_EDIT_CALCULATE_TEMP = 'INIT_EDIT_CALCULATE_TEMP'
// export const AFTER_SUCCESS_INSERT_CALCULATE_INVOICING_ITEM = 'AFTER_SUCCESS_INSERT_CALCULATE_INVOICING_ITEM'
// export const AFTER_SUCCESS_INSERT_CALCULATE_TRANSFER_OUT_ITEM = 'AFTER_SUCCESS_INSERT_CALCULATE_TRANSFER_OUT_ITEM'
export const TRANSFER_OUT_FROM_SEARCH_JUMP_TO_NBZZ = 'TRANSFER_OUT_FROM_SEARCH_JUMP_TO_NBZZ'
export const TRANSFER_OUT_FROM_SEARCH_JUMP_TO_ZJTX = 'TRANSFER_OUT_FROM_SEARCH_JUMP_TO_ZJTX'
export const TRANSFER_OUT_FROM_SEARCH_JUMP_TO_JZSY = 'TRANSFER_OUT_FROM_SEARCH_JUMP_TO_JZSY'
export const TRANSFER_OUT_FROM_SEARCH_JUMP_TO_SYJZ = 'TRANSFER_OUT_FROM_SEARCH_JUMP_TO_SYJZ'
export const COST_TRANSFER_FROM_SEARCH_JUMP_TO_LRLS = 'COST_TRANSFER_FROM_SEARCH_JUMP_TO_LRLS'
export const INVOICE_AUTH_FROM_SEARCH_JUMP_TO_LRLS = 'INVOICE_AUTH_FROM_SEARCH_JUMP_TO_LRLS'
export const INVOICING_FROM_SEARCH_JUMP_TO_LRLS = 'INVOICING_FROM_SEARCH_JUMP_TO_LRLS'
export const PAYMANAGE_FROM_SEARCH_JUMP_TO_LRLS = 'PAYMANAGE_FROM_SEARCH_JUMP_TO_LRLS'
export const TRANSFER_OUT_FROM_SEARCH_JUMP_TO_LRLS = 'TRANSFER_OUT_FROM_SEARCH_JUMP_TO_LRLS'
export const COMMONCHARGE_FROM_SEARCH_JUMP_TO_LRLS = 'COMMONCHARGE_FROM_SEARCH_JUMP_TO_LRLS'
export const INVENTORY_TRANSFER_FROM_SEARCH_JUMP_TO_LRLS = 'INVENTORY_TRANSFER_FROM_SEARCH_JUMP_TO_LRLS'
export const INVENTORY_BALANCE_FROM_SEARCH_JUMP_TO_LRLS = 'INVENTORY_BALANCE_FROM_SEARCH_JUMP_TO_LRLS'
export const CHANGE_CALCULATE_COMMON_STRING = 'CHANGE_CALCULATE_COMMON_STRING'
export const CALCULATE_CHANGE_QUERY = 'CALCULATE_CHANGE_QUERY'
export const GET_CALCULATE_COST_CATEGORY = 'GET_CALCULATE_COST_CATEGORY'
export const INIT_LR_ACOUNT_STATE = 'INIT_LR_ACOUNT_STATE'
export const SAVE_AND_NEW_COMMON_CHARGE = 'SAVE_AND_NEW_COMMON_CHARGE'
export const CHANGE_CALCULATE_ENCLOSURE_LIST = 'CHANGE_CALCULATE_ENCLOSURE_LIST'
export const DELETE_CALCULATE_UPLOAD_FJ_URL = 'DELETE_CALCULATE_UPLOAD_FJ_URL'
export const GET_CAL_LABEL_FETCH = 'GET_CAL_LABEL_FETCH'
export const CHANGE_CAL_TAG_NAME = 'CHANGE_CAL_TAG_NAME'
export const GET_CALCULATE_DEAL_TYPE_CATEGORY = 'GET_CALCULATE_DEAL_TYPE_CATEGORY'
export const AFTER_SUCCESS_INSERT_CALCULATE_LB_ZZ = 'AFTER_SUCCESS_INSERT_CALCULATE_LB_ZZ'
export const EDIT_CALCULATE_GAIN_OR_LOSS = 'EDIT_CALCULATE_GAIN_OR_LOSS'
export const EDIT_CALCULATE_CQZC_GAIN_OR_LOSS = 'EDIT_CALCULATE_CQZC_GAIN_OR_LOSS'
export const GET_PAYMANAGE_LIST = 'GET_PAYMANAGE_LIST'
export const ITIT_PAYMANAGE_LIST = 'ITIT_PAYMANAGE_LIST'
export const GET_CARRYOVER_CATEGORY = 'GET_CARRYOVER_CATEGORY'
export const EDITRUNNING_ITEM_CHECKBOX_CHECK = 'EDITRUNNING_ITEM_CHECKBOX_CHECK'
export const EDITRUNNING_ITEM_CHECKBOX_CHECK_ALL = 'EDITRUNNING_ITEM_CHECKBOX_CHECK_ALL'

export const MODIFY_RUNNING_CALCULATE_INSERT_OR_MODIFY = 'MODIFY_RUNNING_CALCULATE_INSERT_OR_MODIFY'
export const AFTER_SUCCESS_INSERT_CALCULATE_AND_NEW = 'AFTER_SUCCESS_INSERT_CALCULATE_AND_NEW'
export const SWITCH_EDIT_RUNNING_SWITCH_PAGETAB = 'SWITCH_EDIT_RUNNING_SWITCH_PAGETAB'
export const INIT_COST_STOCK_ARRAY = 'INIT_COST_STOCK_ARRAY'
// 存货调拨
export const GET_CANUSE_WAREHOUSE_CARD_LIST = 'GET_CANUSE_WAREHOUSE_CARD_LIST'
export const CHANGE_CANUSE_WAREHOUSE_CARD_LIST = 'CHANGE_CANUSE_WAREHOUSE_CARD_LIST'
export const CHANGE_CANUSE_STOCK_CARD_LIST = 'CHANGE_CANUSE_STOCK_CARD_LIST'
export const CHANGE_ITEM_CHECKBOX_CHECKED = 'CHANGE_ITEM_CHECKBOX_CHECKED'
// 成本结转
export const SELECT_EDIT_CBJZ_ITEM_ALL = 'SELECT_EDIT_CBJZ_ITEM_ALL'
export const SELECT_EDIT_CBJZ_ITEM = 'SELECT_EDIT_CBJZ_ITEM'
export const GET_COST_CARRYOVER_CANUSE_WAREHOUSE_CARD = 'GET_COST_CARRYOVER_CANUSE_WAREHOUSE_CARD'
export const INIT_CATEGORY_FROM_CHANGE_ORISTATE = 'INIT_CATEGORY_FROM_CHANGE_ORISTATE'
export const GET_CARRYOVER_WAREHOUSE = 'GET_CARRYOVER_WAREHOUSE'
export const INIT_CATEGORY_FROM_GET_CATEGORY = 'INIT_CATEGORY_FROM_GET_CATEGORY'
export const CALCULATE_FROM_SEARCH_JUMP_TO_JZCB  = 'CALCULATE_FROM_SEARCH_JUMP_TO_JZCB'
// 存货调拨
export const CLEAR_BALANCETEMP = 'CLEAR_BALANCETEMP'
// export const UPDATE_STOCK_LIST_ITEM = 'UPDATE_STOCK_LIST_ITEM'
// 项目结转
export const XMJZ_GET_CARRYOVER_LIST = 'XMJZ_GET_CARRYOVER_LIST'
// 流水断号
export const INIT_ENCODE_TYPE ='INIT_ENCODE_TYPE'
export const CHANGE_CAN_MODIFY_JRINDEX ='CHANGE_CAN_MODIFY_JRINDEX'
// 收付管理
export const INIT_WRITE_OFF_TYPE = 'INIT_WRITE_OFF_TYPE'
export const CLEAR_FILTER_CONDITION = 'CLEAR_FILTER_CONDITION'
// 进项税额转出
export const GET_MESSAGE_OF_CATEGORY = 'GET_MESSAGE_OF_CATEGORY'
export const TAX_TRANSTER_FROM_SEARCH_JUMP_TO_LRLS = 'TAX_TRANSTER_FROM_SEARCH_JUMP_TO_LRLS'
export const AFTER_GET_JXSE_STOCK_LIST = 'AFTER_GET_JXSE_STOCK_LIST'
// 存货组装拆卸
export const  STOCK_BUILDUP_FROM_SEARCH_JUMP_TO_LRLS = 'STOCK_BUILDUP_FROM_SEARCH_JUMP_TO_LRLS'
export const CHANGE_ITEM_CHECKBOX_ASSEMBLY_CHECKED = 'CHANGE_ITEM_CHECKBOX_ASSEMBLY_CHECKED'
export const CHANGE_ITEM_CHECKBOX_SINGLE_CHECKED = 'CHANGE_ITEM_CHECKBOX_SINGLE_CHECKED'
// 存货投入项目
export const STOCK_INTO_PROJECT_FROM_SEARCH_JUMP_TO_LRLS = 'STOCK_INTO_PROJECT_FROM_SEARCH_JUMP_TO_LRLS'
// 项目结转
export const PROJECT_CARROVER_FROM_SEARCH_JUMP_TO_LRLS = 'PROJECT_CARROVER_FROM_SEARCH_JUMP_TO_LRLS'

// 存货导入
export const AFTER_CALCULATE_INVENTORY_IMPORT = 'AFTER_CALCULATE_INVENTORY_IMPORT'
// 费用分摊
export const CHANGE_PAYMENT_LIST_XMFT = 'CHANGE_PAYMENT_LIST_XMFT'

//盘点
export const CHANGE_ENCLOSURElIST_FILE = 'CHANGE_ENCLOSURElIST_FILE'
export const SAVE_CALCULATE_COUNT = 'SAVE_CALCULATE_COUNT'
export const GET_CANUSE_WAREHOUSE_CARD_CHILD_LIST = 'GET_CANUSE_WAREHOUSE_CARD_CHILD_LIST'
export const GET_CANUSE_WAREHOUSE_CARD_CHILD_LIST_FROM_UNIT = 'GET_CANUSE_WAREHOUSE_CARD_CHILD_LIST_FROM_UNIT'
export const GET_BALANCE_UNIFORM_PRICE = 'GET_BALANCE_UNIFORM_PRICE'
//修改参考单价
export const CHANGE_STOCKCARD_REFERENCE_PRICE_QUNATITY = 'CHANGE_STOCKCARD_REFERENCE_PRICE_QUNATITY'
export const GET_COST_TRANSFER_PRICE = 'GET_COST_TRANSFER_PRICE'
export const CHANGE_BALANCE_ADJUST_PRICE = 'CHANGE_BALANCE_ADJUST_PRICE'

// 结转结转损益 筛选
export const JZJZSY_CHANGE_FILTER_MODAL_CHECKED = 'JZJZSY_CHANGE_FILTER_MODAL_CHECKED'
