export const INIT_KMYEB = 'INIT_KMYEB'
export const TOGGLE_LOWER_BA = 'TOGGLE_LOWER_BA'
export const GET_AC_BA_LIST_FETCH = 'GET_AC_BA_LIST_FETCH'
export const CHANGE_AC_YEB_CHOOSE_VALUE = 'CHANGE_AC_YEB_CHOOSE_VALUE'
