export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_SJB = 'INIT_SJB'
export const CHANGE_SFB_ISSUDATE = 'CHANGE_SFB_ISSUDATE'
export const CHANGE_SFB_RULE_MODAL = 'CHANGE_SFB_RULE_MODAL'
export const GET_SFB_DATA = 'GET_SFB_DATA'
export const CHANGE_SFB_CHOOSE_MORE_PERIODS = 'CHANGE_SFB_CHOOSE_MORE_PERIODS'
export const HANDLE_YJSFB_SHOW_CHILD_LIST = 'HANDLE_YJSFB_SHOW_CHILD_LIST'
