export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const ADD_HOME_TAB_PANE = 'ADD_HOME_TAB_PANE'
export const REMOVE_HOME_TAB_PANE = 'REMOVE_HOME_TAB_PANE'


export const CHANGE_DDREADY_TO_TRUE = 'CHANGE_DDREADY_TO_TRUE'
// export const AFTER_GET_IDENTITY_FETCH = 'AFTER_GET_IDENTITY_FETCH'
export const AFTER_GET_DBLIST_FETCH = 'AFTER_GET_DBLIST_FETCH'
export const GET_PERIOD_FETCH = 'GET_PERIOD_FETCH'
export const AFTER_GET_AC_LIST_FETCH = 'AFTER_GET_AC_LIST_FETCH'
export const AFTER_GET_ASS_FETCH = 'AFTER_GET_ASS_FETCH'
// export const AFTER_SET_DEFAULT_DB_FETCH = 'AFTER_SET_DEFAULT_DB_FETCH'
export const CLEAR_HOME_TAB_PANE = 'CLEAR_HOME_TAB_PANE'
// export const SHOW_CODE_PAGE = 'SHOW_CODE_PAGE'
export const ADD_PAGE_TAB_PANE = 'ADD_PAGE_TAB_PANE'
export const AFTER_SET_DD_CONFIG = 'AFTER_SET_DD_CONFIG'


export const SPREAD_HOME_NAVBER = 'SPREAD_HOME_NAVBER'
export const SHOW_NAVBAR_CHILDREN_LIST = 'SHOW_NAVBAR_CHILDREN_LIST'

export const CLOSE_PAGE_TAB_PANE = 'CLOSE_PAGE_TAB_PANE'
export const CHANGE_HOME_LOCK_FILTER_SHOW = 'CHANGE_HOME_LOCK_FILTER_SHOW'
export const AFTER_CHANGE_LOCK_SECRET = 'AFTER_CHANGE_LOCK_SECRET'

export const CHANGE_PLEASURE_GROUND_MODULE = 'CHANGE_PLEASURE_GROUND_MODULE'

export const GET_ADMIN_FINANCE_NAME_LIST = 'GET_ADMIN_FINANCE_NAME_LIST'
export const CHANGE_LOGIN_GUIDE_STRING = 'CHANGE_LOGIN_GUIDE_STRING'
export const BEFORE_INSERT_GET_MODEL_FCLIST = 'BEFORE_INSERT_GET_MODEL_FCLIST'
export const AFTER_GET_PLAY_SOBMODE_LIST = 'AFTER_GET_PLAY_SOBMODE_LIST'

// 从首页跳转要调用的东西
export const CHANGE_CHAR_DIDMOUNT = 'CHANGE_CHAR_DIDMOUNT'
export const CHANGE_SYXM_CHAR_DIDMOUNT= 'CHANGE_SYXM_CHAR_DIDMOUNT'
export const INIT_LRPZ = 'INIT_LRPZ'
export const CHANGE_LR_FZHS_MODAL_CLEAR = 'CHANGE_LR_FZHS_MODAL_CLEAR'
export const CHANGE_LR_AC_MODAL_CLEAR = 'CHANGE_LR_AC_MODAL_CLEAR'

export const GET_ACCOUNTCONF_ALL_SETTINGS = 'GET_ACCOUNTCONF_ALL_SETTINGS'
export const INIT_LR_ACCOUNT_SETTINGS = 'INIT_LR_ACCOUNT_SETTINGS'
export const SET_INVOIC_ASSLIST_FROM_SETTINGS = 'SET_INVOIC_ASSLIST_FROM_SETTINGS'
export const INIT_LR_ACCOUNT = 'INIT_LR_ACCOUNT'
export const INIT_LR_CALCULATE_STATE = 'INIT_LR_CALCULATE_STATE'
export const INIT_EDIT_RUNNING_SETTINGS = 'INIT_EDIT_RUNNING_SETTINGS'
export const INIT_EIDT_CALCULATE = 'INIT_EIDT_CALCULATE'
export const INIT_EDIT_RUNNING = 'INIT_EDIT_RUNNING'
export const INIT_EDIT_RUNNING_ALL = 'INIT_EDIT_RUNNING_ALL'
export const BEFORE_INSERT_RUNNING = 'BEFORE_INSERT_RUNNING'
export const SOB_OPTION_INIT = 'SOB_OPTION_INIT'
// 前往XXX弹框需要的
export const CALCULATE_FROM_SEARCH_JUMP_TO_EDIT = 'CALCULATE_FROM_SEARCH_JUMP_TO_EDIT'
