export const INIT_MXB = 'INIT_MXB'
export const GET_MXB_ACLIST = 'GET_MXB_ACLIST'
// 此处重复
// export const GET_SUBSIDIARY_LEDGER_FETCH = 'GET_SUBSIDIARY_LEDGER_FETCH'
export const REVERSE_LEDGER_JV_LIST = 'REVERSE_LEDGER_JV_LIST'
export const CHANGE_MXB_BEGIN_DATE = 'CHANGE_MXB_BEGIN_DATE'

export const GET_ZH_DETAIL_LIST = 'GET_ZH_DETAIL_LIST'
export const GET_RUNNING_CATEGORY_DETAIL = 'GET_RUNNING_CATEGORY_DETAIL'
export const ZHMX_GET_RUNNING_ACCOUNT = 'ZHMX_GET_RUNNING_ACCOUNT'

export const CHANGE_ZHMX_COMMON_STRING = 'CHANGE_ZHMX_COMMON_STRING'
export const ZHMX_MENU_DATA = 'ZHMX_MENU_DATA'
export const GET_ZH_RUNNING_CATEGORY_DETAIL = 'GET_ZH_RUNNING_CATEGORY_DETAIL'
export const ZHMX_DETAIL_TRIANGLE_SWITCH = 'ZHMX_DETAIL_TRIANGLE_SWITCH'
