export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ZCFZB = 'INIT_ZCFZB'
// export const BEFORE_GET_BALANCE_SHEET_FETCH = 'BEFORE_GET_BALANCE_SHEET_FETCH'
export const GET_BALANCE_SHEET_FETCH = 'GET_BALANCE_SHEET_FETCH'
export const GET_INIT_BAL_SHEET_VALUE = 'GET_INIT_BAL_SHEET_VALUE'
export const CHANGE_INIT_ZCFZB_AMOUNT = 'CHANGE_INIT_ZCFZB_AMOUNT'
export const CLEAR_INIT_AMOUNT = 'CLEAR_INIT_AMOUNT'
export const SHOW_INIT_ZCFZB = 'SHOW_INIT_ZCFZB'
