export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_KMYEB = 'INIT_KMYEB'
export const GET_AC_BA_LIST_FETCH = 'GET_AC_BA_LIST_FETCH'
export const SHOW_CHILD_ITIEM = 'SHOW_CHILD_ITIEM'
export const CHANGE_KMYE_CHOOSE_MORE_PERIODS = 'CHANGE_KMYE_CHOOSE_MORE_PERIODS'
export const IS_SHOW_ALL = 'IS_SHOW_ALL'
export const GET_PERIOD_FETCH = 'GET_PERIOD_FETCH'
export const CHANGE_AC_YEB_CHOOSE_VALUE = 'CHANGE_AC_YEB_CHOOSE_VALUE'
