export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_SOB_ROLE_LIST_FROM_SOB_OPTION = 'GET_SOB_ROLE_LIST_FROM_SOB_OPTION'
export const SWITCH_SOB_ROLE_CURRENT_ROLE = 'SWITCH_SOB_ROLE_CURRENT_ROLE'
export const SOB_OPTION_INIT = 'SOB_OPTION_INIT'

export const SET_SOB_ROLE_MODULE_LIST_VALUE = 'SET_SOB_ROLE_MODULE_LIST_VALUE'
export const AFTER_MODIFY_SOB_ROLE = 'AFTER_MODIFY_SOB_ROLE'
export const BEFORE_EDIT_SOB_ROLE = 'BEFORE_EDIT_SOB_ROLE'
export const AFTER_INSERT_SOB_ROLE = 'AFTER_INSERT_SOB_ROLE'
export const AFTER_EDIT_SOB_ROLE = 'AFTER_EDIT_SOB_ROLE'
export const CHANGE_SOB_ROLE_COMMON_STRING = 'CHANGE_SOB_ROLE_COMMON_STRING'
