export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_RELATIVEYEB = 'INIT_RELATIVEYEB'
export const GET_PERIOD_AND_RELATIVE_YEB_BALANCE_LIST = 'GET_PERIOD_AND_RELATIVE_YEB_BALANCE_LIST'
export const GET_RELATIVE_YEB_BALANCE_LIST_FROM_SWITCH_PERIOD_OR_RELATIVE = 'GET_RELATIVE_YEB_BALANCE_LIST_FROM_SWITCH_PERIOD_OR_RELATIVE'
export const GET_RELATIVE_YEB_BALANCE_LIST_REFRESH = 'GET_RELATIVE_YEB_BALANCE_LIST_REFRESH'
export const GET_RELATIVE_YEB_CATEGORY_FETCH = 'GET_RELATIVE_YEB_CATEGORY_FETCH'
export const CHANGE_RELATIVE_YEB_CHILD_ITEM_SHOW = 'CHANGE_RELATIVE_YEB_CHILD_ITEM_SHOW'
export const CHANGE_RELATIVE_YEB_CHOOSE_VALUE = 'CHANGE_RELATIVE_YEB_CHOOSE_VALUE'

export const CHANGE_WLYE_MORE_PERIODS = 'CHANGE_WLYE_MORE_PERIODS'
export const GET_WL_TYPE_LIST = 'GET_WL_TYPE_LIST'
export const GET_WL_RELATION_LIST = 'GET_WL_RELATION_LIST'
export const CHANGE_WLYEB_COMMON_STRING = 'CHANGE_WLYEB_COMMON_STRING'
export const INIT_WLYEB = 'INIT_WLYEB'

export const CHANGE_RELATIVE_YEB_ANALYSIS_VALUE = 'CHANGE_RELATIVE_YEB_ANALYSIS_VALUE'
