export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_ZH_BALANCE_LIST = 'GET_ZH_BALANCE_LIST'
export const ACCOUNTCONF_ZH_BALANCE_TRIANGLE_SWITCH = 'ACCOUNTCONF_ZH_BALANCE_TRIANGLE_SWITCH'
export const CHANGE_ZHYE_MORE_PERIODS = 'CHANGE_ZHYE_MORE_PERIODS'
export const INIT_ZHYEB = 'INIT_ZHYEB'
