export const INIT_RELATIVE_YEB = 'INIT_RELATIVE_YEB'

export const GET_RELATIVE_YEB_BALANCE_LIST = 'GET_RELATIVE_YEB_BALANCE_LIST'
export const GET_RELATIVE_BALANCE_CATEGORY = 'GET_RELATIVE_BALANCE_CATEGORY'
export const CHANGE_RELATIVE_CATEGORY_STRING = 'CHANGE_RELATIVE_CATEGORY_STRING'
export const CHANGE_RUNNING_CATEGORY_STRING = 'CHANGE_RUNNING_CATEGORY_STRING'
export const RELATIVE_BALANCE_TRIANGLE_SWITCH = 'RELATIVE_BALANCE_TRIANGLE_SWITCH'
export const CHANGE_RELATIVE_YEB_CHOOSE_VALUE = 'CHANGE_RELATIVE_YEB_CHOOSE_VALUE'
export const CHANGE_RELATIVE_YEB_CHOOSE_DIRCTION = 'CHANGE_RELATIVE_YEB_CHOOSE_DIRCTION'
