export function abstractFunc (oriState, data) {
    const propertyCarryover = data.get('propertyCarryover')
    const categoryName = data.get('categoryName') ?  data.get('categoryName') : data.get('name')
    const propertyPay = data.get('propertyPay')
    const propertyTax = data.get('propertyTax')
    return {
        STATE_YYSR_DJ:'收到预收款',
        STATE_YYSR_XS: categoryName,
        STATE_YYSR_TS: categoryName,
        STATE_YYZC_DJ: '支付预付款',
        STATE_YYZC_GJ: categoryName,
        STATE_YYZC_TG: categoryName,
        STATE_FY_DJ:'支付预付款',
        STATE_FY:`${categoryName}支出`,
        STATE_XC_JT:`计提${{SX_GZXJ:'工资薪金',SX_SHBX:`社会保险'公司'部分`,SX_ZFGJJ:`住房公积金'公司'部分`,SX_FLF: '福利费',SX_QTXC:categoryName}[propertyPay]}`,
        STATE_XC_FF:`${propertyPay=='SX_FLF' ? '支付': '发放'}${{SX_GZXJ:'工资薪金',SX_QTXC:categoryName,SX_FLF: '福利费'}[propertyPay]}`,
        STATE_XC_JN:`缴纳${{SX_SHBX:'社会保险',SX_ZFGJJ:'住房公积金'}[propertyPay]}`,
        STATE_XC_YF:'福利费支出',
        STATE_SF_YJZZS:'预缴增值税',
        STATE_SF_JN:`${{SX_QYSDS:'缴纳企业所得税',SX_GRSF:'代缴个人税费',SX_QTSF:`缴纳${categoryName}`,SX_ZZS:'缴纳增值税'}[propertyTax]}`,
        STATE_SF_JT:`计提${{SX_QYSDS:'企业所得税',SX_GRSF:'个人税费',SX_QTSF:`${categoryName}`,SX_ZZS:'增值税'}[propertyTax]}`,
        STATE_SF_ZCWJZZS: '转出未交增值税',
        STATE_YYWSR:categoryName,
        STATE_YYWZC:categoryName,
        STATE_ZS_SQ:'暂收款',
        STATE_ZS_TH:'暂收款退还',
        STATE_ZF_FC:'暂付款',
        STATE_ZF_SH:'暂付款收回',
        STATE_CQZC_WF:'购进资产支出',
        STATE_CQZC_YF:'购进资产支出',
        STATE_CQZC_WS:'处置资产收入',
        STATE_CQZC_YS:'处置资产收入',
        STATE_JK_YS:'收到借款',
        STATE_JK_JTLX:'计提借款利息',
        STATE_JK_ZFLX:'支付借款利息',
        STATE_JK_YF:'偿还本金支出',
        STATE_TZ_YF:'对外投资支出',
        STATE_TZ_SRGL:'收到投资收益',
        STATE_TZ_JTGL:'计提投资收益',
        STATE_TZ_JTLX:'计提投资收益',
        STATE_TZ_SRLX:'收到投资收益',
        STATE_TZ_WS:'收回投资款',
        STATE_TZ_YS:'收回投资款',
        STATE_ZB_ZZ:'取得货币资本',
        STATE_ZB_ZFLR:'支付分配利润',
        STATE_ZB_LRFP:'计提分配利润',
        STATE_ZB_JZ:'减少注册资本',
        STATE_ZB_ZBYJ: '资本溢价',
        STATE_ZZ: '内部转账',
        STATE_KJFP_XS: '收入开具发票',
        STATE_KJFP_TS: '退销开具红字发票',
        STATE_FPRZ_CG: '增值税专用发票认证',
        STATE_FPRZ_TG: '退购发票认证',
        STATE_CQZC_JZSY: '长期资产处置损益',
        STATE_CQZC_ZJTX: '长期资产折旧摊销',
        STATE_ZCWJZZS: '转出未交增值税',
        STATE_SFGL: '核销账款',
        STATE_GGFYFT: '公共费用分摊',
        STATE_FZSCCB: '项目分摊',
        STATE_ZZFY: '项目分摊',
        STATE_JJFY: '项目分摊',
        STATE_JXZY: '项目分摊',
        STATE_CHDB: '存货调拨',
        STATE_CHYE_CK: '存货余额调整',
        STATE_CHYE_CH: '存货余额调整',
        STATE_CHYE_TYDJ: '存货余额调整',
        STATE_CHYE: '存货余额调整',
        STATE_JXSEZC_FS: '进项税额转出',
        STATE_JXSEZC_TFS: '进项税额转出',
        STATE_CHZZ_ZZCX: '存货组装拆卸',
        STATE_CHZZ_ZZD: '组装单组装',
        STATE_CHYE_ZZD: '组装单组装',
        STATE_CHTRXM: '存货投入使用',
        STATE_XMJZ_JZRK: '结转入库存货',
        STATE_XMJZ_XMJQ: '项目结清',
        STATE_XMJZ_QRSRCB: '确认收入成本',
    }[oriState]
}
