export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ASSETSMXB = 'INIT_ASSETSMXB'
export const GET_ASSESTS_LIST_FETCH = 'GET_ASSESTS_LIST_FETCH'
export const GET_MX_LIST_FETCH = 'GET_MX_LIST_FETCH'
export const CHANGE_ASSETS_MXB_CHOOSE_MORE_PERIODS = 'CHANGE_ASSETS_MXB_CHOOSE_MORE_PERIODS'
export const CHANGE_DETAILCHILDSHOW = 'CHANGE_DETAILCHILDSHOW'

export const GET_ASSESTS_TREE_FETCH = 'GET_ASSESTS_TREE_FETCH'
