export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_CURRENCYYEB = 'INIT_CURRENCYYEB'
export const ALL_GET_CURRENCY_YEB_LIST_FETCH = 'ALL_GET_CURRENCY_YEB_LIST_FETCH'
export const CHANGE_CURRENCY_YEB_SHOW = 'CHANGE_CURRENCY_YEB_SHOW'
export const CHANGE_FC_YEB_CHOOSE_MORE_PERIODS = 'CHANGE_FC_YEB_CHOOSE_MORE_PERIODS'
export const SHOW_CURRENCY_CHILD_ITIEM = 'SHOW_CURRENCY_CHILD_ITIEM'
