export const taxRateList = [
    {key: '2%', value: 2},
    {key: '3%', value: 3},
    {key: '4%', value: 4},
    {key: '5%', value: 5},
    {key: '6%', value: 6},
    {key: '9%', value: 9},
    {key: '10%', value: 10},
    {key: '11%', value: 11},
    {key: '12%', value: 12},
    {key: '13%', value: 13},
    {key: '16%', value: 16},
    {key: '17%', value: 17}
]
export const smallTaxRateList = [
    {key: '2%', value: 2},
    {key: '3%', value: 3},
    {key: '5%', value: 5},
]
export const runningType = {
    "LX_SR":'收入',
    "LX_ZC":'支出',
    "LX_JZCB":'结转成本',
    "LX_CBTH":'成本退回',
    "LX_ZZS_YKP":'已开发票',
    "LX_ZZS_WKP":'未开发票',
    "LX_ZZS_YRZ":'已认证发票',
    "LX_ZZS_WRZ":'未认证发票',
    "LX_TSSF_YKP":'已开发票',
    "LX_TSSF_WKP":'未开发票',
    "LX_TGSF_YRZ":'已认证发票',
    "LX_TGSF_WRZ":'未认证发票',
    "LX_YYSR":'营业收入',
    "LX_PP":'预收款',
    "LX_ZZS":'增值税',
    "LX_YYTS":'退售',
    "LX_TSSF":'退售税费',
    "LX_ARHX":'应收核销',
    "LX_PPHX":'预收核销',
    "LX_TSHX":'退售核销',
    "LX_YYZC":'营业支出',
    "LX_AP":'预付款',
    "LX_ADV":'应付款',
    "LX_YYTG":'退购',
    "LX_TGSF":'退购税费',
    "LX_APHX":'应付核销',
    "LX_ADVHX":'预付核销',
    "LX_TGHX":'退购核销',
    "LX_FYZC":'费用支出',
    "LX_JTGZXJ":'计提工资',
    "LX_GZXJZC":'工资支出',
    "LX_DKGJJ":'代扣公积金',
    "LX_DKSHBX":'代扣社保',
    "LX_DKSDS":'代扣所得税',
    "LX_JTSB":'计提社保',
    "LX_SBZC":'社保支出',
    "LX_DJSB":'代缴社保',
    "LX_JTGJJ":'计提公积金',
    "LX_GJJZC":'公积金支出',
    "LX_DJGJJ":'代缴公积金',
    "LX_FLFZC":'福利费支出',
    "LX_JTQTXC":'计提其他薪酬',
    "LX_QTXC":'其他薪酬支出',
    "LX_YJSF":'预交税费',
    "LX_ZZSZC":'增值税支出',
    "LX_YJDK":'预交抵扣',
    "LX_ZCSDS":'转出所得税',
    "LX_SDSZC":'所得税支出',
    "LX_JTSF":'计提税费',
    "LX_QTSFZC":'其他税费支出',
    "LX_YYWSR":'营业外收入',
    "LX_YYWZC":'营业外支出',
    "LX_ZSKX":'暂收款项',
    "LX_ZSHX":'暂收核销',
    "LX_ZFKX":'暂付款项',
    "LX_ZFHX":'暂付核销',
    "LX_ZCGJ":'资产购进',
    "LX_ZCCZ":'资产处置',
    "LX_JZSY":'处置损益',
    "LX_QDJK":'取得借款',
    "LX_CHLX":'偿还利息',
    "LX_CHBJ":'偿还本金',
    "LX_DWTZ":'对外投资',
    "LX_QDSY":'取得收益',
    "LX_SHTZ":'收回投资',
    "LX_ZZ":'增资',
    "LX_LRFP":'利润分配',
    "LX_JZ":'减资',
    "LX_JZSY_SY":"结转收益",
    "LX_JZSY_SS":"结转损失",
    "LX_JZSY_ZCYZ":"资产原值",
    "LX_JZSY_ZJTX":"累计折旧摊销",
    "LX_JZSY_SJGZ":"升级改造",
    "LX_JZSY_QLSR":"清理收入",
    'LX_FPRZ_CG': '采购发票认证',
    'LX_FPRZ_TG': '退购发票认证',
    'LX_KJFP_XS': '销售开票',
    'LX_KJFP_TS': '退售开票',
    'LX_ZCWJZZS': '转出未交税费',
    'LX_ZFLR': '支付利润',
    'LX_TZ_JTGL': '计提股利',
    'LX_TZ_SRGL': '收入股利',
    'LX_TZ_JTLX': '计提利息',
    'LX_TZ_SRLX': '收入利息',
    'LX_JK_JTLX': '计提利息',
    'LX_JK_ZFLX': '支付利息',
    'LX_NBZZ': '内部转账',
    'LX_NBZR': '内部转账-转入',
    'LX_NBZC': '内部转账-转出',
    'LX_GRSFZC': '个人税费支出',
    'LX_XMGGFYFT': '费用分摊',
    'LX_ZJTX': '折旧摊销'
}
export const urlInsert = {//新增时的url
    'LB_YYSR': 'insertIncome',
    'LB_YYZC': 'insertExpense',
    'LB_FYZC': 'insertCost',
    'LB_XCZC': 'insertPayment',
    'LB_SFZC': 'insertTax',
    'LB_YYWSR': 'insertOutIncome',
    'LB_YYWZC': 'insertOutExpense',
    'LB_ZSKX': 'insertTemporaryReceipt',
    'LB_ZFKX': 'insertTemporaryPay',
    'LB_CQZC': 'insertAssets',
    'LB_JK': 'insertLoan',
    'LB_TZ': 'insertInvest',
    'LB_ZB': 'insertCapital',
    'LB_ZZ': 'insertVirement',
    'LB_KJFP': 'insertBusinessMakeoutItem',
    'LB_FPRZ': 'insertBusinessAuthItem',
    'LB_JZSY': 'insertJzsy',
    'LB_ZJTX': 'insertZjtx',
    'LB_ZCWJZZS': 'insertBusinessTurnoutItem',
    'LB_SFGL': 'insertRunningpayment',
    'LB_JZCB': 'insertCarryoverItem',
    'LB_GGFYFT': 'insertProjectShare',
    'LB_CHDB': 'insertChdb',
    'LB_CHYE': 'insertChye',
    'LB_JXSEZC': 'insertJxsezc',
    'LB_CHZZ': 'insertChzz',
    'LB_CHTRXM': 'insertChtrxm',
    'LB_XMJZ': 'insertXmjz',
}
export const urlModify = {//修改时的url
    'LB_YYSR': 'modifyRunningbusiness',
    'LB_YYZC': 'modifyRunningbusiness',
    'LB_FYZC': 'modifyRunningbusiness',
    'LB_XCZC': 'modifyRunningbusiness',
    'LB_SFZC': 'modifyRunningbusiness',
    'LB_YYWSR': 'modifyRunningbusiness',
    'LB_YYWZC': 'modifyRunningbusiness',
    'LB_ZSKX': 'modifyRunningbusiness',
    'LB_ZFKX': 'modifyRunningbusiness',
    'LB_CQZC': 'modifyRunningbusiness',
    'LB_JK': 'modifyRunningbusiness',
    'LB_TZ': 'modifyRunningbusiness',
    'LB_ZB': 'modifyRunningbusiness',
    'LB_ZZ': 'modifyRunningbusiness',
    'LB_KJFP': 'modifyBusinessMakeoutItem',
    'LB_FPRZ': 'modifyBusinessAuthItem',
    'LB_JZSY': 'modifyJzsy',
    'LB_ZJTX': 'modifyZjtx',
    'LB_ZCWJZZS': 'modifyRunningbusiness',
    'LB_SFGL': 'modifyRunningbusiness',
    'LB_JZCB': 'modifyCarryoverItem',
    'LB_GGFYFT': 'modifyProjectShare',
    'LB_CHDB': 'modifyChdb',
    'LB_CHYE': 'modifyChye',
    'LB_JXSEZC': 'modifyJxsezc',
    'LB_CHZZ': 'modifyChzz',
    'LB_CHTRXM': 'modifyChtrxm',
    'LB_XMJZ': 'modifyXmjz',
}
export const categoryTypeObj = {//类别设置中的字段
    'LB_YYSR': 'acBusinessIncome',
    'LB_YYZC': 'acBusinessExpense',
    'LB_FYZC': 'acCost',
    'LB_XCZC': 'acPayment',
    'LB_SFZC': 'acTax',
    'LB_YYWSR': 'acBusinessOutIncome',
    'LB_YYWZC': 'acBusinessOutExpense',
    'LB_ZSKX': 'acTemporaryReceipt',
    'LB_ZFKX': 'acTemporaryPay',
    'LB_CQZC': 'acAssets',
    'LB_JK': 'acLoan',
    'LB_TZ': 'acInvest',
    'LB_ZB': 'acCapital'
}

export const categoryTypeObjList = [
    'acAssets',
    'acBusinessExpense',
    'acBusinessIncome',
    'acBusinessOutExpense',
    'acBusinessOutIncome',
    'acCapital',
    'acCost',
    'acInvest',
    'acLoan',
    'acPayment',
    'acTax',
    'acTemporaryReceipt',
    'acTemporaryPay'

]

export const runningStateType = {
    STATE_YYSR_DJ:'预收款',
	STATE_YYSR_XS:`销售`,
	STATE_YYSR_TS:`退售`,
	STATE_YYZC_DJ:'预付款',
	STATE_YYZC_GJ:`购进`,
	STATE_YYZC_TG:`退购`,
	STATE_FY_DJ:'预付款',
	STATE_FY:`发生`,
	STATE_XC_JT:`计提`,
	STATE_XC_FF:`发放`,
	STATE_XC_JN:`缴纳`,
	STATE_XC_DK:'代扣',
	STATE_XC_DJ:'代缴',
	STATE_SF_YJZZS:'预缴',
	STATE_SF_JN:`缴纳`,
	STATE_SF_JT:`计提`,
	STATE_SF_SFJM:`减免`,
    STATE_GGFYFT:'损益公共项目',
	STATE_FZSCCB:'辅助生产成本',
	STATE_ZZFY:'制造费用',
    STATE_JJFY: '间接费用',
    STATE_JXZY: '机械作业',
	STATE_ZS_SQ:'收取',
	STATE_ZS_TH:'退还',
	STATE_ZF_FC:'付出',
	STATE_ZF_SH:'收回',
	STATE_JK_JTLX:'计提',
	STATE_JK_ZFLX:'支付利息',
	STATE_TZ_SRGL:'收入股利',
	STATE_TZ_JTGL:'计提',
	STATE_TZ_JTLX:'计提',
	STATE_TZ_SRLX:'收入利息',
	STATE_ZB_ZFLR:'支付利润',
	STATE_ZB_LRFP:'利润分配',
	STATE_SF_ZCWJZZS:'转出未交增值税',
	STATE_KJFP_XS:'销售开票',
	STATE_KJFP_TS:'退销开票',
	STATE_FPRZ_CG:'采购发票认证',
	STATE_FPRZ_TG:'退购发票认证',
    STATE_YYSR_ZJ: '直接结转',
    STATE_CHYE_CK: '按仓库调整',
    STATE_CHYE_TYDJ: '按统一单价调整',
    STATE_CHYE_CH: '按存货调整',
    STATE_CHZZ_ZZCX: '组装拆卸',
    STATE_CHZZ_ZZD: '组装单组装',
    STATE_XMJZ_JZRK: '结转入库',
    STATE_XMJZ_XMJQ: '项目结清',
    STATE_XMJZ_QRSRCB: '确认收入成本',
    STATE_SYJZ_JZBNLR: '结转本年利润',
    STATE_SYJZ_JZCBFY: '结转成本费用',
    STATE_SYJZ_JZSR: '结转收入',

}
