export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ACCOUNTYEB = 'INIT_ACCOUNTYEB'
export const AFTER_GET_PERIOD_AND_ACCOUNT_YEB_BALANCE_LIST = 'AFTER_GET_PERIOD_AND_ACCOUNT_YEB_BALANCE_LIST'
export const CHANGE_ACCOUNT_YEB_CHOOSE_VALUE = 'CHANGE_ACCOUNT_YEB_CHOOSE_VALUE'
