export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'
export const INIT_EDIT_RUNNING = 'INIT_EDIT_RUNNING'
export const INIT_EDIT_RUNNING_ALL = 'INIT_EDIT_RUNNING_ALL'
export const BEFORE_INSERT_RUNNING = 'BEFORE_INSERT_RUNNING'
export const CHANGE_EDIT_RUNNING_COMMON_STRING = 'CHANGE_EDIT_RUNNING_COMMON_STRING'
export const SELECT_EDIT_RUNNING_CATEGORY = 'SELECT_EDIT_RUNNING_CATEGORY'
export const CHANGE_EDIT_RUNNING_ACCOUNT_NAME = 'CHANGE_EDIT_RUNNING_ACCOUNT_NAME'
export const GET_JR_ORI = 'GET_JR_ORI'
export const CHANGE_STATE_INIT_ORITEMP = 'CHANGE_STATE_INIT_ORITEMP'

export const INIT_EDIT_RUNNING_SETTINGS = 'INIT_EDIT_RUNNING_SETTINGS'
export const SET_EDIT_INVOIC_FROM_SETTINGS = 'SET_EDIT_INVOIC_FROM_SETTINGS'
export const CHANGE_EDIT_BILL_STATES = 'CHANGE_EDIT_BILL_STATES'
export const EDIT_CALCULATE_GAIN_OR_LOSS = 'EDIT_CALCULATE_GAIN_OR_LOSS'
export const CHANGE_RUNNING_TAX_RATE = 'CHANGE_RUNNING_TAX_RATE'
export const EDIT_RUNNING_CALCULATE_AMOUNT = 'EDIT_RUNNING_CALCULATE_AMOUNT'
export const CALCULATE_FROM_SEARCH_JUMP_TO_EDIT = 'CALCULATE_FROM_SEARCH_JUMP_TO_EDIT'
export const GET_PREAMOUNT_INFO = 'GET_PREAMOUNT_INFO'
export const SELECT_MODIFY_RUNNING_CATEGORY = 'SELECT_MODIFY_RUNNING_CATEGORY'
export const CHANGE_MODIFY_RUNNING_CATEGORY = 'CHANGE_MODIFY_RUNNING_CATEGORY'
export const CHANGE_EDIT_VIEWA_COMMON_STRING = 'CHANGE_EDIT_VIEWA_COMMON_STRING'
export const CHANGE_PRICE_LIST = 'CHANGE_PRICE_LIST'

// all
export const INIT_EDIT_CALCULATE_TEMP = 'INIT_EDIT_CALCULATE_TEMP'
export const SWITCH_EDIT_RUNNING_SWITCH_PAGETAB = 'SWITCH_EDIT_RUNNING_SWITCH_PAGETAB'
export const MODIFY_RUNNING_CALCULATE_INSERT_OR_MODIFY = 'MODIFY_RUNNING_CALCULATE_INSERT_OR_MODIFY'
export const CHANGE_EDIT_CALCULATE_PAYMENT_TYPE = 'CHANGE_EDIT_CALCULATE_PAYMENT_TYPE'
export const AFTER_SUCCESS_INSERT_CALCULATE_AND_NEW = 'AFTER_SUCCESS_INSERT_CALCULATE_AND_NEW'
// 附件
export const CHANGE_EDIT_RUNNING_ENCLOSURE_LIST = 'CHANGE_EDIT_RUNNING_ENCLOSURE_LIST'
export const GET_EDIT_RUNNING_LABEL_FETCH = 'GET_EDIT_RUNNING_LABEL_FETCH'
export const DELETE_RUNNING_ENCLOSURE_URL = 'DELETE_RUNNING_ENCLOSURE_URL'
export const CHANGE_RUNNING_TAG_NAME = 'CHANGE_RUNNING_TAG_NAME'
export const AFTER_GET_UPLOAD_SIGNATURE = 'AFTER_GET_UPLOAD_SIGNATURE'
export const AFTER_INVENTORY_IMPORT = 'AFTER_INVENTORY_IMPORT'
export const CHANGE_ENCLOSURElIST_FILE = 'CHANGE_ENCLOSURElIST_FILE'
// 设置
export const BEFORE_ADD_INVENTORY_CONF_CARD_RUNNING = 'BEFORE_ADD_INVENTORY_CONF_CARD_RUNNING'
export const BEFORE_ADD_RELATIVE_CARD_FROM_RUNNING = 'BEFORE_ADD_RELATIVE_CARD_FROM_RUNNING'
export const BEFORE_ADD_PROJECT_CARD_FROM_RUNNING = 'BEFORE_ADD_PROJECT_CARD_FROM_RUNNING'

// 项目
export const COMMON_CHARGE_ITEM_CHECKBOX_SELECT = 'COMMON_CHARGE_ITEM_CHECKBOX_SELECT'
export const PROJECT_GET_HTIGH_TYPE = 'PROJECT_GET_HTIGH_TYPE'

// 核算管理日期
export const CHANGE_ORITEMP_ORIDATE = 'CHANGE_ORITEMP_ORIDATE'
// 清空存货列表
export const INIT_COST_STOCK_ARRAY = 'INIT_COST_STOCK_ARRAY'
// 首页跳转
export const CHANGE_EDIT_CALCULATE_NEED_SEND_REQUEST = 'CHANGE_EDIT_CALCULATE_NEED_SEND_REQUEST'
