export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_TAX_CONF = 'INIT_TAX_CONF'
export const CHANGE_TAX_CONF_QUERY = 'CHANGE_TAX_CONF_QUERY'
export const RUNNING_CONF_TAX_RATE_SETTING_SCALE = 'RUNNING_CONF_TAX_RATE_SETTING_SCALE'
export const SELECT_TAX_CONF_ALL_AC = 'SELECT_TAX_CONF_ALL_AC'
export const CHANGE_TAX_CONF_COMMON_STRING = 'CHANGE_TAX_CONF_COMMON_STRING'
