export const INIT_LS_MXB = 'INIT_LS_MXB'
export const GET_MXB_ACLIST = 'GET_MXB_ACLIST'
// 此处重复
// export const GET_SUBSIDIARY_LEDGER_FETCH = 'GET_SUBSIDIARY_LEDGER_FETCH'
export const REVERSE_LEDGER_JV_LIST = 'REVERSE_LEDGER_JV_LIST'
export const CHANGE_MXB_BEGIN_DATE = 'CHANGE_MXB_BEGIN_DATE'

export const GET_DETAIL_LIST = 'GET_DETAIL_LIST'
export const GET_RUNNING_CATEGORY_DETAIL = 'GET_RUNNING_CATEGORY_DETAIL'
export const LSMX_GET_RUNNING_ACCOUNT = 'LSMX_GET_RUNNING_ACCOUNT'

export const CHANGE_LSMX_COMMON_STRING = 'CHANGE_LSMX_COMMON_STRING'
export const LSMX_MENU_DATA = 'LSMX_MENU_DATA'
