export const editRunningTemp = {
    'LB_YYSR': {//营业收入
        'STATE_YYSR_DJ': {//预收
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedAccounts': false,
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_YYSR_XS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'offsetAmount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'beCarryover': false,
            'carryoverCardList': [],
            'stockCardList': [],
            'billList': [],
            'usedStock': false,
            'usedAccounts': false,
        },
        'STATE_YYSR_TS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'offsetAmount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'beCarryover': false,
            'carryoverCardList': [],
            'stockCardList': [],
            'billList': [],
            'usedStock': false,
            'usedAccounts': false,
        }
    },
    'LB_YYZC': {//营业支出
        'STATE_YYZC_DJ': {//预收
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'usedAccounts': false,
        },
        'STATE_YYZC_GJ': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'offsetAmount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'stockCardList': [],
            'billList': [],
            'beCarryover': false,
            'relationCategoryUuid': '',
            'propertyCost': '',
            'usedCarryoverProject': false,
            'carryoverProjectCardList': [],
            'carryoverCardList': [],
            'usedAccounts': false,
        },
        'STATE_YYZC_TG': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'offsetAmount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'stockCardList': [],
            'billList': []
        }
    },
    'LB_FYZC': {//费用支出
        'STATE_FY_DJ': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'usedProject': false,
            'projectCardList': [],
            'usedAccounts': false,
        },
        'STATE_FY': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'offsetAmount': '',
            'oriAbstract': '',
            'propertyCost': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': '',
            'billList': [],
            'usedProject': '',
            'projectCardList': [],
            'usedAccounts': false,
        },
    },
    'LB_SFZC': {//税费支出
        'STATE_SF_YJZZS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
        },
        'STATE_SF_JN': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'beReduceTax': false,
            'reduceAmount': '',
            'offsetAmount': '',
            'accounts': [],
            'pendingStrongList': [],
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_SF_JT': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_SF_SFJM': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
        },
        'STATE_SF_ZCWJZZS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
        }
    },
    'LB_XCZC': {//薪酬支出
        'STATE_XC_JT': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'usedProject': false,
            'projectCardList': [],
            'propertyCost': '',
        },
        'STATE_XC_JN': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'propertyCost': '',
            'payment': {},
            'pendingStrongList': [],
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_XC_FF': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'propertyCost': '',
            'payment': {},
            'pendingStrongList': [],
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_XC_DK': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'propertyCost': '',
            'payment': {},
            'pendingStrongList': [],
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_XC_DJ': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'propertyCost': '',
            'payment': {},
            'pendingStrongList': [],
            'usedProject': false,
            'projectCardList': [],
        },
    },
    'LB_CQZC': {//长期资产
        'STATE_CQZC_YF': {//购进资产
            'oriDate':  '',
            'categoryUuid': '',
            'handleType': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'oriAbstract': '',
            'accounts': [],
            currentCardList: [],
            'usedCurrent': '',
            'billList': [],
            'usedProject': false,
            'projectCardList': [],
        },
        'STATE_CQZC_YS': {//处置
            'oriDate':  '',
            'categoryUuid': '',
            'handleType': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'oriAbstract': '',
            'accounts': [],
            currentCardList: [],
            'usedCurrent': '',
            'billList': [],
            'beCleaning': false,
            "assets":{
                "originalAssetsAmount": "",
                "depreciationAmount": "",
                "cleaningAmount": ""
            },
            'usedProject': '',
            'projectCardList': [],
        },
    },
    'LB_YYWSR': {//营业外收入
        'STATE_YYWSR': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'oriAbstract': '',
            'accounts': [],
            currentCardList: [],
            'usedCurrent': '',
            'usedProject': '',
            'projectCardList': [],
            'billList': [],
        },
    },
    'LB_YYWZC': {//营业外支出
        'STATE_YYWZC': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'currentAmount': '',
            'oriAbstract': '',
            'accounts': [],
            currentCardList: [],
            'usedCurrent': '',
            'usedProject': '',
            'projectCardList': [],
            'billList': [],
        },
    },
    'LB_ZSKX': {//暂收款项
        'STATE_ZS_SQ': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'usedProject':  false,
            'projectCardList': [{
                'cardUuid': '',
                'amount': ''
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZS_TH': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'pendingStrongList': [],
            //'currentCardList': [],
            //'usedCurrent': false,
        }
    },
    'LB_ZFKX': {//暂付款项
        'STATE_ZF_FC': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'usedProject':  false,
            'projectCardList': [{
                'cardUuid': '',
                'amount': ''
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZF_SH': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'pendingStrongList': [],
            //'currentCardList': [],
            //'usedCurrent': false,
        }
    },
    'LB_JK': {//借款
        'STATE_JK_YS': {//取得借款
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_JK_YF': {//偿还本金
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_JK_JTLX': {//偿还利息-计提利息
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'usedProject': '',
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_JK_ZFLX': {//偿还利息-支付利息
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            pendingStrongList: [],
            'usedProject': false,
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
    },
    'LB_TZ': {//投资
        'STATE_TZ_YF': {//对外投资
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_TZ_JTGL': {//取得收益-计提股利
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'usedProject': false,
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_TZ_JTLX': {//取得收益-计提利息
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'usedProject': false,
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_TZ_SRGL': {//取得收益-收入股利
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            pendingStrongList: [],
            'usedProject': false,
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_TZ_SRLX': {//取得收益-收入利息
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            pendingStrongList: [],
            'usedProject': false,
            'projectCardList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_TZ_YS': {//收回投资
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [{
                'accountUuid': '',
                'accountName': '',
                'amount': '',
            }],
            'currentCardList': [],
            'usedCurrent': false,
        },
    },
    'LB_ZB': {//资本
        'STATE_ZB_ZZ': {//增资
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZB_LRFP': {//利润分配
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZB_ZFLR': {//利润分配-支付利润
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'pendingStrongList': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZB_JZ': {//减资
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': false,
        },
        'STATE_ZB_ZBYJ': {
            'oriDate':  '',
            'categoryUuid': '',
            'handleType':  '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
            'currentCardList': [],
            'usedCurrent': false,
        }
    },
    'LB_ZZ': {//内部转账
        'STATE_ZZ': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'accounts': [],
        },
    },
    'LB_KJFP': {//开具发票
        'STATE_KJFP_XS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'billType': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
        },
        'STATE_KJFP_TS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'billType': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
        },
    },
    'LB_FPRZ': {//发票认证
        'STATE_FPRZ_CG': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'billType': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
        },
        'STATE_FPRZ_TG': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'billType': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
        },
    },
    'LB_JZSY': {//结转损益
        'STATE_CQZC_JZSY': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'pendingStrongList': [],
            'assets': {},
            'usedProject': false,
            'projectCardList': [],
        }
    },
    'LB_ZJTX': {//折旧摊销
        'STATE_CQZC_ZJTX': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'amount': '',
            'oriAbstract': '',
            'propertyCost': '',
            'usedProject': false,
            'projectCardList': [],
        }
    },
    'LB_ZCWJZZS': {//转出未缴增值税
        'STATE_ZCWJZZS': {
            'oriDate':  '',
            'categoryUuid': '',
            'oriState': '',
            'oriAbstract': '',
            'handleMonth': '',
        }
    },
    'LB_SFGL': {//收付管理
        'STATE_SFGL': {
            'oriDate':  '',
            'oriState': '',
            'categoryUuid': '',
            'oriAbstract': '',
            'amount': '',
            'moedAmount': '',
            'pendingManageDto': {},
            'accounts': [],
            'currentCardList': [],
            'usedAccounts': false,
        },
        'STATE_SFGL_ML': {
            'oriDate':  '',
            'oriState': '',
            'categoryUuid': '',
            'oriAbstract': '',
            'amount': '',
            'pendingManageDto': {},
            'currentCardList': []
        },
    },
    'LB_JZCB': {//结转成本
        'STATE_YYSR_XS': {
            'oriDate':  '',
            'oriState': '',
            'categoryUuid': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
        'STATE_YYSR_TS': {
            'oriDate':  '',
            'oriState': '',
            'categoryUuid': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
        'STATE_YYSR_ZJ': {
            'oriDate':  '',
            'oriState': '',
            'categoryUuid': '',
            'oriAbstract': '',
            'stockCardList': [],
            'usedProject': false,
            'projectCardList': [],
            propertyCost: '',
        }
    },
    'LB_GGFYFT': {//费用分摊
        'STATE_GGFYFT': {
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'projectCardList': [],
            'usedProject': '',
            'pendingStrongList': [],
            'shareType': '',
        },
        'STATE_FZSCCB': {
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'projectCardList': [],
            'usedProject': '',
            'pendingStrongList': []
        },
        'STATE_ZZFY': {
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'projectCardList': [],
            'usedProject': '',
            'pendingStrongList': []
        },
        'STATE_JJFY': {
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'projectCardList': [],
            'usedProject': '',
            'pendingStrongList': []
        },
        'STATE_JXZY': {
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'projectCardList': [],
            'usedProject': '',
            'pendingStrongList': []
        },
    },
    'LB_CHDB': {//存货调拨
        'STATE_CHDB': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'warehouseCardList': [],
            'stockCardList': [],
        },
    },
    'LB_CHYE': {//存货调整
        'STATE_CHYE': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
        'STATE_CHYE_CK': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
        'STATE_CHYE_CH': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
    },
    'LB_JXSEZC': {//进项税额转出
        'STATE_JXSEZC_FS': {
            'categoryUuid': '',
            'relationCategoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'usedStock': '',
            'stockCardList': [],
            'amount': '',
            'usedProject': '',
            'projectCardList': [],
            'propertyCost': '',
        },
    },
    'LB_CHZZ': {//存货组装
        'STATE_CHZZ_ZZCX': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'stockCardList': [],
            'stockCardOtherList': [],
        },
        'STATE_CHZZ_ZZD': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'stockCardList': [],
        },
    },
    'LB_CHTRXM': {//存货投入项目
        'STATE_CHTRXM': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'usedProject': '',
            'projectCardList': [],
            'stockCardList': [],
        },
    },
    'LB_XMJZ': {//项目结转
        'STATE_XMJZ_JZRK': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'usedProject': '',
            'projectCardList': [],
            'stockCardList': [],
        },
        'STATE_XMJZ_XMJQ': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'usedProject': '',
            'projectCardList': [],
            'stockCardList': [],
            'amount': '',
            'currentAmount':  '',
        },
        'STATE_XMJZ_QRSRCB': {
            'categoryUuid': '',
            'oriDate':  '',
            'oriState': '',
            'oriAbstract': '',
            'usedProject': '',
            'projectCardList': [],
            'amount': '',
            'currentAmount':  '',
        },
    },

}
