export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'
export const SWITCH_APPROVAL_ACTIVE_PAGE = 'SWITCH_APPROVAL_ACTIVE_PAGE'
export const INIT_APPROVAL_CONFIG = 'INIT_APPROVAL_CONFIG'

export const GET_APPROVAL_MODEL_LIST = 'GET_APPROVAL_MODEL_LIST'
export const GET_APPROVAL_DETAIL_LIST = 'GET_APPROVAL_DETAIL_LIST'
export const INIT_APPROVALTEMPLATE = 'INIT_APPROVALTEMPLATE'
export const INIT_APPROVAL_CARD = 'INIT_APPROVAL_CARD'
export const GET_APPROVAL_BASIC_COMPONENT_LIST = 'GET_APPROVAL_BASIC_COMPONENT_LIST'

// 模板
export const CANCEL_MODIFY_APPROVAL_TEMPLATE = 'CANCEL_MODIFY_APPROVAL_TEMPLATE'
export const CHANGE_APPROVAL_BASE_SETTING_COMMON_STRING = 'CHANGE_APPROVAL_BASE_SETTING_COMMON_STRING'
export const CHANGE_APPROVAL_BASE_SETTING_JR_CATEGORY = 'CHANGE_APPROVAL_BASE_SETTING_JR_CATEGORY'
export const ADD_APPROVAL_FORM_COMPONENT = 'ADD_APPROVAL_FORM_COMPONENT'
export const DELETE_APPROVAL_FORM_COMPONENT = 'DELETE_APPROVAL_FORM_COMPONENT'
export const CHANGE_APPROVAL_FORM_OPTION_STRING = 'CHANGE_APPROVAL_FORM_OPTION_STRING'
export const ADJUST_POSITION_APPROVAL_FORM_COMPONENT = 'ADJUST_POSITION_APPROVAL_FORM_COMPONENT'
export const BEFOR_INSERT_OR_MODIFY_APPROVAL_TEMPLATE = 'BEFOR_INSERT_OR_MODIFY_APPROVAL_TEMPLATE'
export const CHANGE_APPROVAL_MODEL_STATE = 'CHANGE_APPROVAL_MODEL_STATE'

// 明细
export const CANCEL_MODIFY_APPROVAL_CARD = 'CANCEL_MODIFY_APPROVAL_CARD'
export const BEFORE_INSERT_OR_MODIFY_DETAIL = 'BEFORE_INSERT_OR_MODIFY_DETAIL'
export const CHANGE_APPROVAL_CARD_COMMON_STRING = 'CHANGE_APPROVAL_CARD_COMMON_STRING'
export const ADD_APPROVAL_CARD_FORM_COMPONENT = 'ADD_APPROVAL_CARD_FORM_COMPONENT'
export const DELETE_APPROVAL_CARD_FORM_COMPONENT = 'DELETE_APPROVAL_CARD_FORM_COMPONENT'
export const CHANGE_APPROVAL_CARD_FORM_OPTION_STRING = 'CHANGE_APPROVAL_CARD_FORM_OPTION_STRING'
export const ADJUST_POSITION_APPROVAL_CARD_COMPONENT = 'ADJUST_POSITION_APPROVAL_CARD_COMPONENT'

// 卡片
export const AFTER_GET_APPROVAL_PROJECT_CARD_LIST = 'AFTER_GET_APPROVAL_PROJECT_CARD_LIST'
export const AFTER_GET_APPROVAL_CONTACT_CARD_LIST = 'AFTER_GET_APPROVAL_CONTACT_CARD_LIST'
export const AFTER_GET_APPROVAL_STOCK_CARD_LIST = 'AFTER_GET_APPROVAL_STOCK_CARD_LIST'
export const AFTER_GET_APPROVAL_WAREHOUSE_CARD_TREE = 'AFTER_GET_APPROVAL_WAREHOUSE_CARD_TREE'
export const CHANGE_APPROVAL_TEMP_COMMON_STRING = 'CHANGE_APPROVAL_TEMP_COMMON_STRING'


