export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'
export const INIT_PZ_BOMB = 'INIT_PZ_BOMB'
export const PZBOMB_REVIEWEDBY_VC = 'PZBOMB_REVIEWEDBY_VC'
export const CANCEL_PZBOMB_REVIEWEDBY_VC = 'CANCEL_PZBOMB_REVIEWEDBY_VC'
