
export const INIT_CXPZ = 'INIT_CXPZ'
export const GET_VC_LIST_FETCH = 'GET_VC_LIST_FETCH'
export const DELETE_VC_FETCH = 'DELETE_VC_FETCH'
export const CHANGE_ALL_VC_CHECKBOX_DISPLAY = 'CHANGE_ALL_VC_CHECKBOX_DISPLAY'
export const CANCEL_CHANGE_VC_CHECKBOX_DISPALY = 'CANCEL_CHANGE_VC_CHECKBOX_DISPALY'
export const SELECT_VC_ALL = 'SELECT_VC_ALL'
export const SELECT_VC = 'SELECT_VC'
export const REVERSE_VC_LIST = 'REVERSE_VC_LIST'
export const AFTER_PAGING_VC = 'AFTER_PAGING_VC'
export const CXPZ_CHANGE_DATA = 'CXPZ_CHANGE_DATA'


export const PUSH_VOUCHER_TO_LRPZ_REDUCER = 'PUSH_VOUCHER_TO_LRPZ_REDUCER'
export const GET_PERIOD_FETCH = 'GET_PERIOD_FETCH'
export const CHANGE_FJGL_ISSUEDATE = 'CHANGE_FJGL_ISSUEDATE'
