export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ASSETSYEB = 'INIT_ASSETSYEB'
export const GET_DETAIL_ASSETS_FETCH = 'GET_DETAIL_ASSETS_FETCH'
export const CHANGE_ASSETSYEB_CHOOSE_MORE_PERIODS = 'CHANGE_ASSETSYEB_CHOOSE_MORE_PERIODS'
export const CHANGE_DETAILCHILDSHOW = 'CHANGE_DETAILCHILDSHOW'
