export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const GET_ZH_DETAIL_LIST = 'GET_ZH_DETAIL_LIST'
export const INIT_ZH_DETAIL_ACCOUNT_LIST = 'INIT_ZH_DETAIL_ACCOUNT_LIST'
export const GET_ZH_RUNNING_CATEGORY_DETAIL = 'GET_ZH_RUNNING_CATEGORY_DETAIL'
export const CHANGE_ZH_DETAIL_ACCOUNT_COMMON_STRING = 'CHANGE_ZH_DETAIL_ACCOUNT_COMMON_STRING'
export const CHANGE_ZHMX_MORE_PERIODS = 'CHANGE_ZHMX_MORE_PERIODS'
export const ACCOUNTCONF_DETAIL_TRIANGLE_SWITCH = 'ACCOUNTCONF_DETAIL_TRIANGLE_SWITCH'

export const INIT_ZHMXB = 'INIT_ZHMXB'
