export const SWITCH_LOADING_MASK = 'SWITCH_LOADING_MASK'

export const INIT_ASSMXB = 'INIT_ASSMXB'
export const GET_ASS_MXB_ACLIST_TFETCH = 'GET_ASS_MXB_ACLIST_TFETCH'
export const GET_REPORT_ASS_DETAIL_FETCH = 'GET_REPORT_ASS_DETAIL_FETCH'
export const CHANGE_ASSMXB_CHOOSEPERIODS = 'CHANGE_ASSMXB_CHOOSEPERIODS'
